version: '3'
services:
  next:
    build: .
    expose: 
      - 8080
    ports:
      - '8080:8080'
    container_name: next-observacion
    stdin_open: true
    command: npm run start
    volumes:
      - ./:/usr/src/inventory
      - /usr/src/inventory/node_modules
